# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9efa569ff17632bc6b91573ab897c9b739c65bb8a5f7ce35267cfe043a629e6a0e0e5ea4f7c46457a467b3864fbc8b89f6d5f105cb2e71d535541fe53b6c8f4f

test:
  secret_key_base: 1227668cbd0fc89c8b4963e224fd5eae476a9c72b09dd8f94b2227b7976b2086ebcf4ca0dcd3cb911fccf58b6fdbb4ffa81e17fe2b13ea395c6005139a7fab70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
